# Generated by Django 3.2.19 on 2023-06-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('size', models.CharField(max_length=10)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
    ]
